spring.application.name=Enotes_API_Service

# Database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/enotes
spring.datasource.username=root
spring.datasource.password=Gulu@6200
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate configuration (optional, but recommended)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
